// [snowpack] add styles to the page (skip if no document exists)
if (typeof document !== 'undefined') {
  const code = ":root {\n  --bg-color: #132d43;\n  --primary: #67cff9;\n  --border-color: #2a465c;\n  --success: #198754;\n  --info: #0dcaf0;\n  --warning: #ffc107;\n  --danger: #dc3545;\n  --light: #f8f9fa;\n  --dark: #212529;\n  --font-sans-serif: system-ui, -apple-system, 'Segoe UI', Roboto,\n    'Helvetica Neue', Arial, 'Noto Sans', 'Liberation Sans', sans-serif,\n    'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  --font-monospace: SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono',\n    'Courier New', monospace;\n}\n\nbody {\n  padding: 0;\n  margin: 0;\n  font-family: var(--font-sans-serif);\n  font-size: 16px;\n  background-color: var(--bg-color);\n}\n\ncode {\n  font-family: var(--font-monospace);\n}\n\n*,\n*::before,\n*::after {\n  box-sizing: border-box;\n}\n\ninput {\n  display: block;\n  width: 100%;\n  padding: 0.25rem 0.75rem;\n  font-size: 1rem;\n  font-weight: 400;\n  line-height: 1.5;\n  color: var(--dark);\n  background-color: var(--light);\n  background-clip: padding-box;\n  border: 1px solid var(--primary);\n  appearance: none;\n  border-radius: 0.25rem;\n  transition: border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out;\n}\n\ninput:focus {\n  color: var(--dark);\n  background-color: var(--light);\n  border-color: var(--border-color);\n  outline: 0;\n  box-shadow: 0 0 0 0.25rem rgba(13, 110, 253, 0.25);\n}\n\ninput::placeholder {\n  color: rgba(0, 0, 0, 0.5);\n  opacity: 1;\n}\n\ninput:disabled,\ninput[readonly] {\n  background-color: rgba(255, 255, 255, 0.5);\n  opacity: 1;\n  cursor: not-allowed;\n  border-color: var(--dark);\n}\n\n.form-group {\n  margin: 0 0 1rem 0;\n}\n\n.form-group > label {\n  display: inline-block;\n  padding-left: 0.2rem;\n  margin-bottom: 0.2rem;\n  font-size: 0.75rem;\n}\n";

  const styleEl = document.createElement("style");
  const codeEl = document.createTextNode(code);
  styleEl.type = 'text/css';
  styleEl.appendChild(codeEl);
  document.head.appendChild(styleEl);
}