name: Development artifacts workflow

on:
  push:
    branches:
      - "main"

jobs:
  test-app:
    runs-on: ubuntu-latest
    services:
      ganache:
        image: trufflesuite/ganache:latest
        ports:
          - 7545:8545
    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
      - uses: actions/checkout@v2

      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Truffle
        run: npm run install:truffle:global

      - name: Truffle Test
        run: CI=true truffle test

      - name: Install root dependencies
        run: npm ci

      - name: Audit root dependencies
        run: |
          npm audit
          npm audit --json --only=prod


      - name: Install client dependencies
        run: |
          cd client
          npm ci

      - name: Audit client dependencies
        run: |
          cd client
          npm audit
          npm audit --json --only=prod

      - name: Lint
        run: npm run lint

      - name: Unit Tests
        run: |
          cd client
          npm run test

      - name: Truffle deploy contract
        run: truffle deploy

      - name: Should build successfully
        run: |
          cd client
          npm run build

      - name: Run local for e2e tests
        run: |
          cd client
          npm run test:e2e:serve &

      - name: E2E Tests
        run: |
          cd client
          npm run test:e2e

  deploy-client:
    runs-on: ubuntu-latest
    needs: [ test-app ]
    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
      - uses: actions/checkout@v2

      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install client dependencies
        run: |
          cd client
          npm ci

      - name: Build client for gh pages
        run: |
          cd client
          npm run build:gh:pages

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./client/build

