name: Pull request workflow
on: [ pull_request ]

jobs:
  contract:
    runs-on: ubuntu-latest
    services:
      ganache:
        image: trufflesuite/ganache:latest
        ports:
          - 7545:8545
    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
      - uses: actions/checkout@v2

      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Truffle
        run: npm install truffle -g

      - name: Truffle Test
        run: CI=true truffle test

  client:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
      - uses: actions/checkout@v2

      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install root dependencies
        run: npm ci

      - name: Audit root dependencies
        run: |
          npm audit
          npm audit --json --only=prod


      - name: Install client dependencies
        run: |
          cd client
          npm ci

      - name: Audit client dependencies
        run: |
          cd client
          npm audit
          npm audit --json --only=prod

      - name: Lint
        run: npm run lint

      - name: Unit Tests
        run: |
          cd client
          npm run test

      - name: Should build successfully
        run: |
          cd client
          npm run build

      - name: Run local for e2e tests
        run: |
          cd client
          npm run test:e2e:serve &

      - name: E2E Tests
        run: |
          cd client
          npm run test:e2e
